### ISSUE TITLE
Enable advanced stats for node

### ISSUE THREAD

**Issue by bst27** [FreiFunkMuenster/node-stats#9]
Please enable advanced stats for node with id **647002f78225**.

**Comment by MPW1412** [comment]
In deinem Knoten ist - entgegen der Vorschrift des PPA - keine Kontaktadresse hinterlegt. Daher können wir deine Anfrage auch nicht verifizieren. Also nicht sicherstellen, dass der Knoten wirklich dir gehört.

Bitte trage deine Emailadresse wie vorgesehen im Knoten ein, dann schreiben wir dich an, und nach erfolgter Verifikation, dass du der Eigentümer bist, aktivieren wir gerne die erweiterten Statistiken.

Viele Grüße
Matthias
